### ISSUE TITLE
ubuntu npm run dev 出现错误

### ISSUE THREAD

**Issue by guwenbin1991** [jiakeqi/douban#4]
系统：ubuntu 16.04
node: 6.9.1

安装好redis-server之后，npm install之后没有问题，
但是在npm run dev时出现以下错误：
Entry module not found: Error: Can't resolve 'babel' in '/home/pro/github/vue_source/douban'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' prefix when using loaders.
You need to specify 'babel-loader' instead of 'babel'.
resolve 'babel' in '/home/pro/github/vue_source/douban'
Parsed request is a module

Failed at the douban@ dev script 'node server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

在终端下直接node server.js 出现同样的错误，

**Comment by jiakeqi** [comment]
谢谢你的反馈 😀 已经 fix 这个 bug,
在这个 commit 中
https://github.com/jiakeqi/douban/commit/a3df2fc889b4f0d346ef310cd268ef5d3e7eadbe

**Comment by guwenbin1991** [comment]
问题已解决，thanks
